### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by masylum** [vowsjs/kyuri#12] opened 2010-10-21 16:30 UTC
What's the status of the project? I would love to participate but I don't where to start as I never worked with cucumber before.

**Comment by Marak** [comment] 2010-10-21 16:35
It's under active development, we are just a bit side tracked at the moment launching nodejitsu. 

You should start out by cloning the kyuri repo and then running the test suite using vows. 

from indexzero: 

With respect to Kyuri, there are some small changes to the lexer that need to get implemented so we can become an upstream dependency to Cucumber itself. The project lead, Aslak Hellesøy has expressed a strong interest in merging in Kyuri as the Javascript Gherkin parser.

**Comment by indexzero** [comment] 2010-10-21 20:14
Thanks for the comment, but I'm closing this issue since it's not a bug or feature request.

**Closed as completed by indexzero** 2010-10-21 20:14 UTC
